export const ENTER_MOVIES = 'ENTER_MOVIES'
export const ENTER_MOVIES_SUCCESS = 'ENTER_MOVIES_SUCCESS'
export const ENTER_MOVIE = 'ENTER_MOVIE'
export const ENTER_MOVIE_SUCCESS = 'ENTER_MOVIE_SUCCESS'
